DECLARE @ORDERCODE AS VARCHAR(100)
SET @ORDERCODE = 'BWJJ1474~20191001~N-O'


    SELECT OG.SXEXTORDERID,
		STR(ABD.SXBUNDLEID) AS SXBUNDLEID,
		X1.ALLOCBEGDATE,
		X1.ALLOCENDDATE,
		X1.SXALLOCOPTION,
		RI.SXCODE,
		RI.SXSOURCE,
		RI.BILLINGACCOUNT,
		ISNULL(RI.SVITEMID, '') AS SVITEMID,
		ISNULL(RI.SVORDERID, '') AS SVORDERID,
		RI.CHARGETYPE,
		ISNULL(RI.UDAC, '') AS UDAC,
		ISNULL(RI.PRINTCODE, '') AS PRINTCODE,
		ISNULL(RI.DIRECTORYISSUENUMBER, 0) AS DIRECTORYISSUENUMBER,
		CAST(RI.SXTERMINDAYS AS INT) AS POB_SXTERMINDAYS,
		CONCAT(YEAR(RF.SXSTARTDATE), RIGHT(CONCAT(0, MONTH(RF.SXSTARTDATE)), 2), RIGHT(CONCAT(0, DAY(RF.SXSTARTDATE)), 2)) AS STARTDATE,
		CONCAT(YEAR(RF.SXENDDATE), RIGHT(CONCAT(0, MONTH(RF.SXENDDATE)), 2), RIGHT(CONCAT(0, DAY(RF.SXENDDATE)), 2)) AS ENDDATE,
		ISNULL(RI.PRODUCTTYPE, '') AS PRODUCTTYPE,
		RI.ACCOUNTTYPE,
		RI.SXSTATUS,
		RI.SXTRXORIGINALAMOUNT AS POB_SXTRXORIGINALAMOUNT,
		RI.SXSSPUNITAMOUNT,
		ABD.SXEXCLUDED,
		ABD.SXORIGAMOUNT,
		CASE
		   WHEN ABD.SXEXCLUDED = 'Y' THEN 0 
		   ELSE COALESCE(ABD.SXREMAININGPCT,100)
		 END AS SXREMAININGPCT,
		--ABD.SXREMAININGPCT,
		ABD.SXTERMINDAYS,
		ABD.SXFMV,
		CASE 
			WHEN ABD.SXEXCLUDED = 'Y' THEN 0 
			ELSE ROUND(ABD.SXORIGAMOUNT * COALESCE(ABD.SXREMAININGPCT,100) / 100, 2) 
		  END AS AMOUNTTOALLOCATE,
		ABD.SXALLOCAMOUNT,
		ABD.SXTRXAMOUNT,
		CASE 
				WHEN RFD.SXACTUALDATE IS NULL THEN CONCAT(YEAR(RFD.SXRECOGNITIONDATE), RIGHT(CONCAT(0, MONTH(RFD.SXRECOGNITIONDATE)), 2), RIGHT(CONCAT(0, DAY(RFD.SXRECOGNITIONDATE)), 2)) 
				ELSE CONCAT(YEAR(RFD.SXRECOGNITIONDATE), RIGHT(CONCAT(0, MONTH(RFD.SXRECOGNITIONDATE)), 2), RIGHT(CONCAT(0, DAY(RFD.SXRECOGNITIONDATE)), 2)) 
			END AS OLDSXRECOGNITIONDATE,
		CASE WHEN RFD.SXACTUALDATE IS NULL THEN 
				 CONCAT(YEAR(RFD.SXRECOGNITIONDATE),RIGHT(CONCAT(0,MONTH(RFD.SXRECOGNITIONDATE)),2),'-F')
 			 ELSE CASE WHEN CONCAT(YEAR(RFD.SXRECOGNITIONDATE),RIGHT(CONCAT(0,MONTH(RFD.SXRECOGNITIONDATE)),2)) >= 
						   CONCAT(YEAR(JE.SXJEDATE),RIGHT(CONCAT(0,MONTH(JE.SXJEDATE)),2)) 
						THEN CONCAT(YEAR(JE.SXJEDATE),RIGHT(CONCAT(0,MONTH(JE.SXJEDATE)),2),'-R') 
					  ELSE CONCAT(YEAR(JE.SXJEDATE),RIGHT(CONCAT(0,MONTH(JE.SXJEDATE)),2),'-C') 
				 END
		END SXRECOGNITIONDATE,
		CASE WHEN RFD.SXACTUALDATE IS NULL AND 
	              CONCAT(YEAR(RFD.SXRECOGNITIONDATE),RIGHT(CONCAT(0,MONTH(RFD.SXRECOGNITIONDATE)),2),RIGHT(CONCAT(0, DAY(RFD.SXRECOGNITIONDATE)),2)) >= X1.ALLOCBEGDATE AND
				  CONCAT(YEAR(RFD.SXRECOGNITIONDATE),RIGHT(CONCAT(0,MONTH(RFD.SXRECOGNITIONDATE)),2),RIGHT(CONCAT(0, DAY(RFD.SXRECOGNITIONDATE)),2))  <= X1.ALLOCENDDATE 
	              THEN RFD.SXTRXAMOUNT
		     WHEN RFD.SXACTUALDATE IS NOT NULL AND
			      CONCAT(YEAR(JE.SXJEDATE),RIGHT(CONCAT(0,MONTH(JE.SXJEDATE)),2),RIGHT(CONCAT(0, DAY(JE.SXJEDATE)),2)) >= X1.ALLOCBEGDATE AND
				  CONCAT(YEAR(JE.SXJEDATE),RIGHT(CONCAT(0,MONTH(JE.SXJEDATE)),2),RIGHT(CONCAT(0, DAY(JE.SXJEDATE)),2))  <= X1.ALLOCENDDATE 
				  THEN RFD.SXTRXAMOUNT
		     ELSE 0 
		END AS FORECASTAMOUNT  
		,RFD.SXSTATUS AS FORECASTSTATUS  

	FROM DBO.SXORDERGROUPS OG 
		INNER JOIN DBO.SXREVITEMTOGROUPS RIG 
		  ON RIG.SXGROUPID = OG.SXID AND RIG.SXTYPE = 'O' AND 
		     RIG.SXROWDELETED = 'N' AND OG.SXROWDELETED = 'N' 
		INNER JOIN DBO.SXALLOCBUNDLEDETS ABD 
		  ON RIG.SXREVITEMID = ABD.SXREVITEMID AND 
		     ABD.SXROWDELETED = 'N' 
		INNER JOIN 
		(
		SELECT 
		    X.SXBUNDLEID,
			CONCAT(YEAR(X.SXALLOCDATE), RIGHT(CONCAT(0, MONTH(X.SXALLOCDATE)), 2), RIGHT(CONCAT(0, DAY(X.SXALLOCDATE)), 2)) AS ALLOCBEGDATE,
			CASE 
					WHEN CONCAT(YEAR(LEAD(X.SXALLOCDATE - 1, 1) 
					OVER (ORDER BY X.SXBUNDLEID)
					), RIGHT(CONCAT(0, MONTH(LEAD(X.SXALLOCDATE - 1, 1) 
							OVER (ORDER BY X.SXBUNDLEID)
							)), 2), RIGHT(CONCAT(0, DAY(LEAD(X.SXALLOCDATE - 1, 1) 
							OVER (ORDER BY X.SXBUNDLEID)
							)), 2)) = '00' THEN CONCAT(YEAR(CURRENT_TIMESTAMP), RIGHT(CONCAT(0, MONTH(CURRENT_TIMESTAMP)), 2), RIGHT(CONCAT(0, DAY(CURRENT_TIMESTAMP)), 2)) 
					ELSE CONCAT(YEAR(LEAD(X.SXALLOCDATE - 1, 1) 
					OVER (ORDER BY X.SXBUNDLEID)
					), RIGHT(CONCAT(0, MONTH(LEAD(X.SXALLOCDATE - 1, 1) 
							OVER (ORDER BY X.SXBUNDLEID)
							)), 2), RIGHT(CONCAT(0, DAY(LEAD(X.SXALLOCDATE - 1, 1) 
							OVER (ORDER BY X.SXBUNDLEID)
							)), 2)) 
				END AS ALLOCENDDATE,
	        X.SXALLOCOPTION
		FROM 
		   (
			SELECT DISTINCT 
			    STR(ABD.SXBUNDLEID) AS SXBUNDLEID,
				AB.SXALLOCDATE,
				AB.SXALLOCOPTION
			FROM DBO.SXORDERGROUPS OG 
				INNER JOIN DBO.SXREVITEMTOGROUPS RIG ON RIG.SXGROUPID = OG.SXID AND RIG.SXTYPE = 'O' AND RIG.SXROWDELETED = 'N' AND OG.SXROWDELETED = 'N' 
				INNER JOIN DBO.SXALLOCBUNDLEDETS ABD ON RIG.SXREVITEMID = ABD.SXREVITEMID AND ABD.SXSTATUS = 'A' AND ABD.SXROWDELETED = 'N' 
				INNER JOIN DBO.SXALLOCATIONBUNDLES AB ON AB.SXID = ABD.SXBUNDLEID AND AB.SXSTATUS = 'A' AND AB.SXROWDELETED = 'N' 
			WHERE OG.SXEXTORDERID = @ORDERCODE
					) X ) X1

	      ON X1.SXBUNDLEID = ABD.SXBUNDLEID AND
		     X1.ALLOCBEGDATE <= X1.ALLOCENDDATE
		INNER JOIN DBO.SXREVENUEITEMS RI 
		  ON RIG.SXREVITEMID = RI.SXID AND 
		     RI.SXROWDELETED = 'N' AND
		     CHARINDEX('.',RI.SXCODE) = 0
		INNER JOIN DBO.SXREVENUEFORECASTS RF 
		  ON RF.SXREVENUEITEMID = RI.SXID AND 
		     RF.SXROWDELETED = 'N' 
		INNER JOIN DBO.SXREVFORECASTDETAILS RFD 
		  ON RFD.SXREVFORECASTID = RF.SXID AND 
		     RFD.SXROWDELETED = 'N' 
		LEFT JOIN DBO.SXJOURNALENTRY JE 
		  ON JE.SXID = RFD.SXJEENTRYID AND 
			 JE.SXROWDELETED = 'N' 
	WHERE OG.SXEXTORDERID = @ORDERCODE AND
	  X1.ALLOCBEGDATE < X1.ALLOCENDDATE 
	GROUP BY 
	   OG.SXEXTORDERID, 
	   STR(ABD.SXBUNDLEID), 
	   X1.ALLOCBEGDATE, 
	   X1.ALLOCENDDATE, 
	   X1.SXALLOCOPTION,
	   RI.SXCODE, 
	   RI.SXSOURCE, 
	   RI.BILLINGACCOUNT, 
	   ISNULL(RI.SVITEMID, ''), 
	   ISNULL(RI.SVORDERID, ''), 
	   RI.CHARGETYPE, 
	   ISNULL(RI.UDAC, ''), 
	   ISNULL(RI.PRINTCODE, ''), 
	   ISNULL(RI.DIRECTORYISSUENUMBER, 0), 
	   CAST(RI.SXTERMINDAYS AS INT), 
	   CONCAT(YEAR(RF.SXSTARTDATE), RIGHT(CONCAT(0, MONTH(RF.SXSTARTDATE)), 2), RIGHT(CONCAT(0, DAY(RF.SXSTARTDATE)), 2)), 
	   CONCAT(YEAR(RF.SXENDDATE), RIGHT(CONCAT(0, MONTH(RF.SXENDDATE)), 2), RIGHT(CONCAT(0, DAY(RF.SXENDDATE)), 2)), 
	   ISNULL(RI.PRODUCTTYPE, ''), 
	   RI.ACCOUNTTYPE, 
	   RI.SXSTATUS, 
	   RI.SXTRXORIGINALAMOUNT, 
	   RI.SXSSPUNITAMOUNT, 
	   ABD.SXEXCLUDED, 
	   ABD.SXORIGAMOUNT, 
	   CASE
		   WHEN ABD.SXEXCLUDED = 'Y' THEN 0 
		   ELSE COALESCE(ABD.SXREMAININGPCT,100)
		 END, 
	   ABD.SXTERMINDAYS, 
	   ABD.SXFMV, 
	   CASE 
		 WHEN ABD.SXEXCLUDED = 'Y' THEN 0 
		      ELSE ROUND(ABD.SXORIGAMOUNT * COALESCE(ABD.SXREMAININGPCT,100) / 100, 2) 
		END, 
	   ABD.SXALLOCAMOUNT, 
	   ABD.SXTRXAMOUNT, 
	   CASE 
		    WHEN RFD.SXACTUALDATE IS NULL THEN CONCAT(YEAR(RFD.SXRECOGNITIONDATE), RIGHT(CONCAT(0, MONTH(RFD.SXRECOGNITIONDATE)), 2), RIGHT(CONCAT(0, DAY(RFD.SXRECOGNITIONDATE)), 2)) 
				ELSE CONCAT(YEAR(RFD.SXRECOGNITIONDATE), RIGHT(CONCAT(0, MONTH(RFD.SXRECOGNITIONDATE)), 2), RIGHT(CONCAT(0, DAY(RFD.SXRECOGNITIONDATE)), 2)) 
			END,
	   CASE WHEN RFD.SXACTUALDATE IS NULL THEN 
				 CONCAT(YEAR(RFD.SXRECOGNITIONDATE),RIGHT(CONCAT(0,MONTH(RFD.SXRECOGNITIONDATE)),2),'-F')
 			ELSE CASE WHEN CONCAT(YEAR(RFD.SXRECOGNITIONDATE),RIGHT(CONCAT(0,MONTH(RFD.SXRECOGNITIONDATE)),2)) >= 
						   CONCAT(YEAR(JE.SXJEDATE),RIGHT(CONCAT(0,MONTH(JE.SXJEDATE)),2)) 
						THEN CONCAT(YEAR(JE.SXJEDATE),RIGHT(CONCAT(0,MONTH(JE.SXJEDATE)),2),'-R') 
					  ELSE CONCAT(YEAR(JE.SXJEDATE),RIGHT(CONCAT(0,MONTH(JE.SXJEDATE)),2),'-C')
				 END
		END
	   ,RFD.SXTRXAMOUNT
	   ,CASE WHEN RFD.SXACTUALDATE IS NULL AND 
	              CONCAT(YEAR(RFD.SXRECOGNITIONDATE),RIGHT(CONCAT(0,MONTH(RFD.SXRECOGNITIONDATE)),2),RIGHT(CONCAT(0, DAY(RFD.SXRECOGNITIONDATE)),2)) >= X1.ALLOCBEGDATE AND
				  CONCAT(YEAR(RFD.SXRECOGNITIONDATE),RIGHT(CONCAT(0,MONTH(RFD.SXRECOGNITIONDATE)),2),RIGHT(CONCAT(0, DAY(RFD.SXRECOGNITIONDATE)),2))  <= X1.ALLOCENDDATE 
	              THEN RFD.SXTRXAMOUNT
		     WHEN RFD.SXACTUALDATE IS NOT NULL AND 
			      CONCAT(YEAR(JE.SXJEDATE),RIGHT(CONCAT(0,MONTH(JE.SXJEDATE)),2),RIGHT(CONCAT(0, DAY(JE.SXJEDATE)),2)) >= X1.ALLOCBEGDATE AND
				  CONCAT(YEAR(JE.SXJEDATE),RIGHT(CONCAT(0,MONTH(JE.SXJEDATE)),2),RIGHT(CONCAT(0, DAY(JE.SXJEDATE)),2))  <= X1.ALLOCENDDATE 
				  THEN RFD.SXTRXAMOUNT
		     ELSE 0 
		END
      ,RFD.SXSTATUS


